/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_ctimer.h"
#include "fsl_clock.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals_cm33_core0 functional group */
/* Definition of peripheral ID */
#define CTIMER1_MOTOR_A_PERIPHERAL CTIMER1
/* Timer tick frequency in Hz (input frequency of the timer) */
#define CTIMER1_MOTOR_A_TICK_FREQ 1000000UL
/* Timer tick period in ns (input period of the timer) */
#define CTIMER1_MOTOR_A_TICK_PERIOD 1000UL
/* Definition of PWM period channel. */
#define CTIMER1_MOTOR_A_PWM_PERIOD_CH kCTIMER_Match_0
/* Definition of channel 2 ID */
#define CTIMER1_MOTOR_A_MATCH_0_CHANNEL kCTIMER_Match_2
/* Definition of peripheral ID */
#define CTIMER0_MOTOR_B_PERIPHERAL CTIMER0
/* Timer tick frequency in Hz (input frequency of the timer) */
#define CTIMER0_MOTOR_B_TICK_FREQ 1000000UL
/* Timer tick period in ns (input period of the timer) */
#define CTIMER0_MOTOR_B_TICK_PERIOD 1000UL
/* Definition of PWM period channel. */
#define CTIMER0_MOTOR_B_PWM_PERIOD_CH kCTIMER_Match_0
/* Definition of channel 3 ID */
#define CTIMER0_MOTOR_B_MATCH_0_CHANNEL kCTIMER_Match_3

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const ctimer_config_t CTIMER1_MOTOR_A_config;
extern const ctimer_match_config_t CTIMER1_MOTOR_A_Match_0_config;
extern const ctimer_config_t CTIMER0_MOTOR_B_config;
extern const ctimer_match_config_t CTIMER0_MOTOR_B_Match_0_config;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals_cm33_core0(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
